In [16]:
import pandas as pd
import numpy as np
from azure.storage.blob import BlobServiceClient
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from keras.preprocessing.image import load_img, img_to_array
import json
import os
from PIL import Image
import matplotlib.pyplot as plt
import io  # Used to convert bytes to a file-like object
from PIL import Image



# Parse Images to bring them into the right format for model training

### 1. Access to Azure data storage

In [17]:
#set up storage
#connection_string = 
container_name = "publicdata"

#create client
blob_service_client = BlobServiceClient.from_connection_string(connection_string)
container_client = blob_service_client.get_container_client(container_name)

### 2. Encode labels in the right way

In [18]:
preprocessed = pd.read_csv('labeled_data.csv')

order_of_labels = ["Human", "Barrier", "Bike", "Motorcycle", "Truck", "Car", "Trafficcone", "NoDetec"]

preprocessed['Labels'] = preprocessed[order_of_labels].values.tolist()
preprocessed.drop(columns=['Unnamed: 0'], inplace=True)

preprocessed

filename  Human  Barrier  Bike  \
0   samples/CAM_BACK/n003-2018-01-03-12-03-23+0800...      1        0     0   
1   samples/CAM_BACK/n003-2018-01-08-11-30-34+0800...      1        1     0   
2   samples/CAM_BACK/n003-2018-07-12-15-40-35+0800...      1        0     0   
3   samples/CAM_BACK/n005-2018-06-14-20-11-03+0800...      0        0     0   
4   samples/CAM_BACK/n008-2018-06-04-16-30-00-0400...      0        0     0   
5   samples/CAM_BACK/n009-2018-05-08-15-52-41-0400...      0        0     1   
6   samples/CAM_BACK/n010-2018-08-27-12-00-23+0800...      1        1     0   
7   samples/CAM_BACK/n013-2018-08-20-14-38-24+0800...      0        0     1   
8   samples/CAM_BACK/n013-2018-08-21-11-46-25+0800...      1        0     0   
9   samples/CAM_BACK/n013-2018-08-28-16-04-27+0800...      1        0     0   
10  samples/CAM_BACK/n013-2018-08-29-11-41-15+0800...      1        1     1   
11  samples/CAM_BACK_LEFT/n008-2018-05-30-16-31-36...      0        0     0   
12  samples/CAM_BACK_LEFT/n010-2018-07-05-14-36-33...      1        0     1   
13  samples/CAM_BACK_LEFT/n010-2018-07-06-11-01-46...      0        0     0   
14  samples/CAM_BACK_LEFT/n010-2018-08-27-15-10-53...      1        0     1   
15  samples/CAM_BACK_LEFT/n013-2018-08-02-14-08-14...      1        0     0   
16  samples/CAM_BACK_LEFT/n013-2018-08-03-14-44-49...      1        0     0   
17  samples/CAM_BACK_LEFT/n013-2018-08-16-16-15-38...      0        0     0   
18  samples/CAM_BACK_LEFT/n013-2018-08-27-16-40-42...      1        0     1   
19  samples/CAM_BACK_LEFT/n015-2018-09-19-11-19-35...      1        0     0   
20  samples/CAM_BACK_LEFT/n016-2018-07-10-16-55-57...      1        0     0   
21  samples/CAM_BACK_RIGHT/n003-2018-01-04-11-23-2...      1        0     1   
22  samples/CAM_BACK_RIGHT/n008-2018-05-21-11-06-5...      0        1     0   
23  samples/CAM_BACK_RIGHT/n008-2018-05-30-15-20-5...      0        0     0   
24  samples/CAM_BACK_RIGHT/n008-2018-05-30-16-31-3...      1        0     0   
25  samples/CAM_BACK_RIGHT/n013-2018-08-02-13-54-0...      0        0     0   
26  samples/CAM_BACK_RIGHT/n013-2018-08-27-11-35-1...      1        0     1   
27  samples/CAM_BACK_RIGHT/n014-2018-06-25-21-03-4...      0        0     0   
28  samples/CAM_BACK_RIGHT/n015-2018-09-13-15-25-5...      1        1     0   
29  samples/CAM_BACK_RIGHT/n016-2018-07-06-12-06-1...      1        0     1   
30  samples/CAM_FRONT/n006-2018-09-17-12-15-45-040...      0        1     0   
31  samples/CAM_FRONT/n008-2018-03-14-15-16-29-040...      0        0     0   
32  samples/CAM_FRONT/n008-2018-05-21-11-06-59-040...      0        0     0   
33  samples/CAM_FRONT/n008-2018-09-18-14-18-33-040...      0        1     0   
34  samples/CAM_FRONT/n009-2018-09-12-09-59-51-040...      1        1     0   
35  samples/CAM_FRONT/n013-2018-08-01-16-46-39+080...      0        0     1   
36  samples/CAM_FRONT/n013-2018-08-20-14-38-24+080...      0        0     0   
37  samples/CAM_FRONT/n016-2018-07-04-10-44-39+080...      1        0     0   
38  samples/CAM_FRONT_LEFT/n010-2018-09-17-15-57-1...      1        0     0   
39  samples/CAM_FRONT_LEFT/n013-2018-08-16-16-15-3...      0        0     0   
40  samples/CAM_FRONT_LEFT/n013-2018-08-29-14-19-1...      1        0     0   
41  samples/CAM_FRONT_LEFT/n013-2018-09-03-14-54-4...      1        0     0   
42  samples/CAM_FRONT_LEFT/n013-2018-09-04-13-30-5...      1        1     0   
43  samples/CAM_FRONT_RIGHT/n004-2018-01-04-11-05-...      1        1     0   
44  samples/CAM_FRONT_RIGHT/n005-2018-06-14-20-11-...      0        0     0   
45  samples/CAM_FRONT_RIGHT/n008-2018-05-21-11-06-...      1        0     0   
46  samples/CAM_FRONT_RIGHT/n013-2018-08-27-14-41-...      1        1     0   
47  samples/CAM_FRONT_RIGHT/n013-2018-08-27-15-47-...      1        1     0   
48  samples/CAM_FRONT_RIGHT/n015-2018-09-05-12-12-...      1        1     0   
49  samples/CAM_FRONT_RIGHT/n016-2018-07-10-11-22-...      0        0     0   

    Motorcycle 

### 3. Define function loading, preprocessing and encoding image based on filename

In [36]:
import io
from PIL import Image
import numpy as np
import zlib
image = "resized_samples/CAM_BACK_LEFT/n013-2018-08-03-14-44-49+0800__CAM_BACK_LEFT__1533278795447155.jpg"

def load_image(path):
    blob_client = container_client.get_blob_client(path)
    # Download the blob's content as bytes
    blob_data = blob_client.download_blob().chunks()  # Read the entire blob content
    # Convert the blob data into a file-like object using io.BytesIO
    image_data = io.BytesIO(b"".join(blob_data))
    # Open the image using PIL.Image
    image = Image.open(image_data)
    return image_data

def preprocess_ecode(image_data):
    # Open the image using PIL.Image
    image = Image.open(image_data)
    image = image.resize((256, 256))
    grayscale_image = image.convert("L")

    # Convert the image to a NumPy array
    grayscale_image = np.array(grayscale_image)
    grayscale_array = grayscale_image / 255.0

    return grayscale_array


def from_path_to_encoded(path):
    #load image from path
    image = load_image(path)
    #apply preprocessing function
    preped = preprocess_ecode(image)
    return preped 

#test
x = from_path_to_encoded(image)

(256, 256)

### 4. Deploy the encoding function on each row

In [35]:
preprocessed["image"] = preprocessed["filename"].apply(from_path_to_encoded)
preprocessed

[[0.28235294 0.30196078 0.30196078 ... 0.70588235 0.70980392 0.61176471]
 [0.26666667 0.29803922 0.29411765 ... 0.70196078 0.70980392 0.61176471]
 [0.23529412 0.29411765 0.29411765 ... 0.69803922 0.65882353 0.56078431]
 ...
 [0.50196078 0.50196078 0.50588235 ... 0.46666667 0.4745098  0.41176471]
 [0.51372549 0.51372549 0.51764706 ... 0.4745098  0.48235294 0.42352941]
 [0.38823529 0.38823529 0.38823529 ... 0.36078431 0.36470588 0.3254902 ]]
[[0.21960784 0.22745098 0.23921569 ... 0.36078431 0.34509804 0.30196078]
 [0.21960784 0.21960784 0.23137255 ... 0.34901961 0.34901961 0.29411765]
 [0.22745098 0.21960784 0.22352941 ... 0.34509804 0.34117647 0.28627451]
 ...
 [0.62352941 0.62745098 0.63529412 ... 0.67843137 0.67843137 0.59215686]
 [0.64313725 0.64313725 0.65490196 ... 0.67843137 0.68627451 0.6       ]
 [0.47843137 0.48235294 0.49019608 ... 0.50980392 0.51372549 0.45490196]]
[[0.46666667 0.4627451  0.4627451  ... 0.75686275 0.76470588 0.6745098 ]
 [0.4627451  0.46666667 0.47058824 ... 

filename  Human  Barrier  Bike  \
0   samples/CAM_BACK/n003-2018-01-03-12-03-23+0800...      1        0     0   
1   samples/CAM_BACK/n003-2018-01-08-11-30-34+0800...      1        1     0   
2   samples/CAM_BACK/n003-2018-07-12-15-40-35+0800...      1        0     0   
3   samples/CAM_BACK/n005-2018-06-14-20-11-03+0800...      0        0     0   
4   samples/CAM_BACK/n008-2018-06-04-16-30-00-0400...      0        0     0   
5   samples/CAM_BACK/n009-2018-05-08-15-52-41-0400...      0        0     1   
6   samples/CAM_BACK/n010-2018-08-27-12-00-23+0800...      1        1     0   
7   samples/CAM_BACK/n013-2018-08-20-14-38-24+0800...      0        0     1   
8   samples/CAM_BACK/n013-2018-08-21-11-46-25+0800...      1        0     0   
9   samples/CAM_BACK/n013-2018-08-28-16-04-27+0800...      1        0     0   
10  samples/CAM_BACK/n013-2018-08-29-11-41-15+0800...      1        1     1   
11  samples/CAM_BACK_LEFT/n008-2018-05-30-16-31-36...      0        0     0   
12  samples/CAM_BACK_LEFT/n010-2018-07-05-14-36-33...      1        0     1   
13  samples/CAM_BACK_LEFT/n010-2018-07-06-11-01-46...      0        0     0   
14  samples/CAM_BACK_LEFT/n010-2018-08-27-15-10-53...      1        0     1   
15  samples/CAM_BACK_LEFT/n013-2018-08-02-14-08-14...      1        0     0   
16  samples/CAM_BACK_LEFT/n013-2018-08-03-14-44-49...      1        0     0   
17  samples/CAM_BACK_LEFT/n013-2018-08-16-16-15-38...      0        0     0   
18  samples/CAM_BACK_LEFT/n013-2018-08-27-16-40-42...      1        0     1   
19  samples/CAM_BACK_LEFT/n015-2018-09-19-11-19-35...      1        0     0   
20  samples/CAM_BACK_LEFT/n016-2018-07-10-16-55-57...      1        0     0   
21  samples/CAM_BACK_RIGHT/n003-2018-01-04-11-23-2...      1        0     1   
22  samples/CAM_BACK_RIGHT/n008-2018-05-21-11-06-5...      0        1     0   
23  samples/CAM_BACK_RIGHT/n008-2018-05-30-15-20-5...      0        0     0   
24  samples/CAM_BACK_RIGHT/n008-2018-05-30-16-31-3...      1        0     0   
25  samples/CAM_BACK_RIGHT/n013-2018-08-02-13-54-0...      0        0     0   
26  samples/CAM_BACK_RIGHT/n013-2018-08-27-11-35-1...      1        0     1   
27  samples/CAM_BACK_RIGHT/n014-2018-06-25-21-03-4...      0        0     0   
28  samples/CAM_BACK_RIGHT/n015-2018-09-13-15-25-5...      1        1     0   
29  samples/CAM_BACK_RIGHT/n016-2018-07-06-12-06-1...      1        0     1   
30  samples/CAM_FRONT/n006-2018-09-17-12-15-45-040...      0        1     0   
31  samples/CAM_FRONT/n008-2018-03-14-15-16-29-040...      0        0     0   
32  samples/CAM_FRONT/n008-2018-05-21-11-06-59-040...      0        0     0   
33  samples/CAM_FRONT/n008-2018-09-18-14-18-33-040...      0        1     0   
34  samples/CAM_FRONT/n009-2018-09-12-09-59-51-040...      1        1     0   
35  samples/CAM_FRONT/n013-2018-08-01-16-46-39+080...      0        0     1   
36  samples/CAM_FRONT/n013-2018-08-20-14-38-24+080...      0        0     0   
37  samples/CAM_FRONT/n016-2018-07-04-10-44-39+080...      1        0     0   
38  samples/CAM_FRONT_LEFT/n010-2018-09-17-15-57-1...      1        0     0   
39  samples/CAM_FRONT_LEFT/n013-2018-08-16-16-15-3...      0        0     0   
40  samples/CAM_FRONT_LEFT/n013-2018-08-29-14-19-1...      1        0     0   
41  samples/CAM_FRONT_LEFT/n013-2018-09-03-14-54-4...      1        0     0   
42  samples/CAM_FRONT_LEFT/n013-2018-09-04-13-30-5...      1        1     0   
43  samples/CAM_FRONT_RIGHT/n004-2018-01-04-11-05-...      1        1     0   
44  samples/CAM_FRONT_RIGHT/n005-2018-06-14-20-11-...      0        0     0   
45  samples/CAM_FRONT_RIGHT/n008-2018-05-21-11-06-...      1        0     0   
46  samples/CAM_FRONT_RIGHT/n013-2018-08-27-14-41-...      1        1     0   
47  samples/CAM_FRONT_RIGHT/n013-2018-08-27-15-47-...      1        1     0   
48  samples/CAM_FRONT_RIGHT/n015-2018-09-05-12-12-...      1        1     0   
49  samples/CAM_FRONT_RIGHT/n016-2018-07-10-11-22-...      0        0     0   

    Motorcycle 

### export dataframe to csv so that it can be read in the file for model building

In [37]:
preprocessed.to_csv("preprocessed.csv")